name = "jingangchong-app"

[pages]
pages_build_output_dir = "out"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

[vars]
NEXT_PUBLIC_FEISHU_APP_ID = ""
FEISHU_APP_SECRET = ""
NEXT_PUBLIC_FEISHU_BASE_ID = ""
NEXT_PUBLIC_FEISHU_TABLE_ID = ""