name = "jingangchong-app"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[pages]
pages_build_output_dir = ".vercel/output/static"

[functions]
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[pages.functions]]
pattern = "api/*"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[pages.functions]]
pattern = "owner/*"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[pages.functions]]
pattern = "status/*"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
